#!/usr/bin/env bash
# install a Nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mv /var/www/html/index.nginx-debian.html /var/www/html/save_index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
