#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer lb-01 server
apt-get update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  abybells-alx-frontend
        bind *:80
        mode http
        default_backend abybells-alx-backend
        
backend abybells-alx-backend
        balance roundrobin
        server 18348-web-01 18.206.214.0:80 check
        server 18348-web-02 3.236.64.48:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
