#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file
# displays Username, user id, home directory path for the user

while read -r entry
do
    echo "$entry" | cut -d":" -f1,3,6
done < /etc/passwd
