#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
# displays hours from 0 to 12
# displays minutes from 1 to 59

i=0
while [ $i -lt 13 ]
do
j=1
    echo "Hour: $i"
    while [ $j -lt 60 ]
    do
	echo $j
	j=$(( j+1 ))
    done
    i=$(( i+1 ))
done
